export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST'
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS'
export const FETCH_MENU_ERROR = 'FETCH_MENU_ERROR'

export const FETCH_TABLES_REQUEST = 'FETCH_TABLES_REQUEST'
export const FETCH_TABLES_SUCCESS = 'FETCH_TABLES_SUCCESS'
export const FETCH_TABLES_ERROR = 'FETCH_TABLES_ERROR'

export const SELECT_TABLE = 'SELECT_TABLE'

export const FETCH_CHECKS_REQUEST = 'FETCH_CHECKS_REQUEST'
export const FETCH_CHECKS_SUCCESS = 'FETCH_CHECKS_SUCCESS'
export const FETCH_CHECKS_ERROR = 'FETCH_CHECKS_ERROR'

export const FETCH_NEW_CHECK_REQUEST = 'FETCH_NEW_CHECK_REQUEST'
export const FETCH_NEW_CHECK_SUCCESS = 'FETCH_NEW_CHECK_SUCCESS'
export const FETCH_NEW_CHECK_ERROR = 'FETCH_NEW_CHECK_ERROR';
