export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST'
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS'
export const FETCH_MENU_ERROR = 'FETCH_MENU_ERROR'

export const FETCH_TABLES_REQUEST = 'FETCH_TABLES_REQUEST'
export const FETCH_TABLES_SUCCESS = 'FETCH_TABLES_SUCCESS'
export const FETCH_TABLES_ERROR = 'FETCH_TABLES_ERROR'

export const SELECT_TABLE = 'SELECT_TABLE'
